info:
    description: Access various FBI data endpoints.
    title: FBI_API
    version: 1.0.0
openapi: 3.1.0
paths:
    /@artcrimes:
        get:
            operationId: Artcrimes_get
            parameters:
                - description: Field to filter by (e.g., location)
                  in: query
                  name: field
                  required: true
                  schema:
                    default: location
                    type: string
                - description: Value to filter by
                  in: query
                  name: value
                  required: true
                  schema:
                    default: New York
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                description: new desc
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    items:
                                        description: Return the items in an array.
                                        items:
                                            description: Array item
                                            properties:
                                                additionalData:
                                                    description: Additional data to include in the response.
                                                    type: string
                                                crimeCategory:
                                                    description: Category of crime being reported.
                                                    type: string
                                                description:
                                                    description: Description of the API response.
                                                    type: string
                                                id:
                                                    description: ID of the resource.
                                                    type: string
                                                idInAgency:
                                                    description: Unique identifier assigned to an entity in the agency.
                                                    type: string
                                                images:
                                                    description: Return a list of images.
                                                    items:
                                                        description: Array item
                                                        properties:
                                                            caption:
                                                                description: Caption for the new API.
                                                                type: string
                                                            large:
                                                                description: Specify the size of the response. Use "large" to receive a large response.
                                                                type: string
                                                            original:
                                                                description: Original data from the API response.
                                                                type: string
                                                            thumb:
                                                                description: Thumbnail image URL
                                                                type: string
                                                        type: object
                                                    type: array
                                                isStealth:
                                                    description: Specify if the API should operate in stealth mode. Set to true for stealth mode, false otherwise. Default is false.
                                                    type: boolean
                                                maker:
                                                    description: Maker information for the new API.
                                                    type: string
                                                materials:
                                                    description: Materials used in the API response.
                                                    type: string
                                                measurements:
                                                    description: Measurements to retrieve from the API.
                                                    type: string
                                                modified:
                                                    description: Specify if the API has been modified or not. The value should be a string indicating the modification status.
                                                    type: string
                                                path:
                                                    description: Path to the resource.
                                                    type: string
                                                period:
                                                    description: Specify the time period for the data, in format "yyyy-mm-dd" to "yyyy-mm-dd".
                                                    type: string
                                                referenceNumber:
                                                    description: Unique reference number for the API response.
                                                    type: string
                                                title:
                                                    description: Title of the item.
                                                    type: string
                                                uid:
                                                    description: Unique identifier for the user.
                                                    type: string
                                                url:
                                                    description: URL of the API.
                                                    type: string
                                            type: object
                                        type: array
                                    page:
                                        description: Page number to retrieve data from the API.
                                        type: number
                                    total:
                                        description: Total number of items returned by the API.
                                        type: number
                                type: object
                    description: new desc
                default:
                    description: ""
            summary: new api
    /@wanted:
        get:
            operationId: Wanted_get
            parameters:
                - description: Field to filter by (e.g., title)
                  in: query
                  name: field
                  required: true
                  schema:
                    type: string
                - description: Value to filter by
                  in: query
                  name: value
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                description: new desc
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                description: new param
                                items:
                                    type: object
                                type: array
                    description: new desc
                default:
                    description: ""
            summary: new api
servers:
    - url: https://api.fbi.gov
