components:
    examples:
        getQuote:
            value:
                ReqExample:
                    format: json
                    lang: en
                    method: getQuote
                RespExample:
                    quoteAuthor: Moncure Conway
                    quoteLink: http://forismatic.com/en/5a4cb85d24/
                    quoteText: 'The best thing in every noble dream is the dreamer... '
                    senderLink: ""
                    senderName: ""
    schemas:
        QuoteResponse:
            description: new param
            properties:
                quoteAuthor:
                    description: new param
                    type: string
                quoteText:
                    description: new param
                    type: string
                senderLink:
                    description: new param
                    type: string
                senderName:
                    description: new param
                    type: string
            type: object
        QuoteResponseHTML:
            description: new param
            type: string
        QuoteResponseJSONP:
            description: new param
            properties:
                callback:
                    description: new param
                    type: string
                data:
                    $ref: '#/components/schemas/QuoteResponse'
            type: object
        QuoteResponseText:
            description: new param
            type: string
        QuoteResponseXML:
            description: new param
            properties:
                forismatic:
                    description: new param
                    properties:
                        quote:
                            description: new param
                            properties:
                                quoteAuthor:
                                    description: new param
                                    type: string
                                quoteText:
                                    description: new param
                                    type: string
                                senderLink:
                                    description: new param
                                    type: string
                                senderName:
                                    description: new param
                                    type: string
                            type: object
                    type: object
            type: object
info:
    description: The Forismatic API provides random quotes and expressions. It supports multiple response formats and languages.
    title: Forismatic Quotes
    version: 1.0.0
openapi: 3.1.0
paths:
    /:
        get:
            operationId: getQuote
            parameters:
                - description: The method name to invoke.
                  in: query
                  name: method
                  required: true
                  schema:
                    default: getQuote
                    type: string
                    x-global-disable: true
                - description: The response format.
                  in: query
                  name: format
                  required: true
                  schema:
                    default: json
                    type: string
                - description: Numeric key which influences the choice of quotation. The maximum length is 6 characters.
                  in: query
                  name: key
                  schema:
                    type: integer
                - description: The response language.
                  in: query
                  name: lang
                  required: true
                  schema:
                    default: en
                    type: string
                - description: Callback function name, used for jsonp format only.
                  in: query
                  name: jsonp
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                description: new desc
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    quoteAuthor:
                                        description: Author of the selected quote
                                        type: string
                                    quoteLink:
                                        description: URL link to the full quote.
                                        type: string
                                    quoteText:
                                        description: Text of the selected quote.
                                        type: string
                                    senderLink:
                                        description: The link to the sender of the quote in string format.
                                        type: string
                                    senderName:
                                        description: The name of the sender of the quote.
                                        type: string
                                type: object
                    description: new desc
                default:
                    description: ""
            summary: Selects a random quote using a passed numeric key. If the key is not specified, the server generates a random key. The key influences the choice of quotation.
servers:
    - url: https://api.forismatic.com/api/1.0
