components:
    examples:
        getHipsterIpsum:
            value:
                ReqExample:
                    paras: 4
                    start-with-lorem: false
                    type: hipster-centric
                RespExample:
                    error: 'Response form is not json. Failed to parse: json: cannot unmarshal array into Go value of type map[string]interface {}'
info:
    description: |-
        Hipster Ipsum Plugin


        The Hipster Ipsum Plugin generates placeholder text with a hipster twist, ideal for modern designs and web content.

        Operations:

        getHipsterIpsum: Generate Hipster Ipsum text.
        Parameters:

        type (string, required): Type of text (hipster-latin, hipster-centric).
        paras (integer, optional, default=4): Number of paragraphs.
        start-with-lorem (boolean, optional, default=false): Start with "Lorem ipsum".
        Example:

        json
        Copy code
        {
          "type": "hipster-latin",
          "paras": 3,
          "start-with-lorem": false
        }
        Output is an array of generated paragraphs.

        assisted.space/tree
    title: Hipster Ipsum
    version: 1.0.0
openapi: 3.1.0
paths:
    /api/:
        get:
            operationId: getHipsterIpsum
            parameters:
                - description: Type of text to generate.
                  in: query
                  name: type
                  schema:
                    type: string
                - description: Number of paragraphs to generate.
                  in: query
                  name: paras
                  schema:
                    default: 4
                    type: integer
                - description: Whether to start with "I'm baby..."
                  in: query
                  name: start-with-lorem
                  schema:
                    default: false
                    type: boolean
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                description: new desc
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    text:
                                        type: string
                                type: object
                    description: new desc
                default:
                    description: ""
            summary: Retrieve random Hipster Ipsum text.
servers:
    - url: https://hipsum.co
