components:
    examples:
        guerrillaMailApi:
            value:
                ReqExample:
                    agent: Mozilla/5.0
                    f: get_email_address
                    ip: 127.0.0.1
                RespExample:
                    alias: tz7gpr+3dr1h6zzhf5s8
                    email_addr: rvmdvpvg@guerrillamailblock.com
                    email_timestamp: 1723874939
                    sid_token: 6dfn5ptgffloudm0371pbsjm7e
    schemas:
        Email:
            description: new param
            properties:
                mail_date:
                    description: new param
                    type: string
                mail_excerpt:
                    description: new param
                    type: string
                mail_from:
                    description: new param
                    type: string
                mail_id:
                    description: new param
                    type: integer
                mail_read:
                    description: new param
                    type: integer
                mail_subject:
                    description: new param
                    type: string
                mail_timestamp:
                    description: new param
                    type: integer
            type: object
        EmailAddress:
            description: new param
            properties:
                email_addr:
                    description: new param
                    type: string
                email_timestamp:
                    description: new param
                    type: integer
                s_active:
                    description: new param
                    type: string
                s_date:
                    description: new param
                    type: string
                s_time:
                    description: new param
                    type: integer
                s_time_expires:
                    description: new param
                    type: integer
            type: object
        EmailList:
            description: new param
            properties:
                count:
                    description: new param
                    type: integer
                email:
                    description: new param
                    type: string
                list:
                    description: new param
                    items:
                        $ref: '#/components/schemas/Email'
                    type: array
                ts:
                    description: new param
                    type: integer
            type: object
        ExtendResponse:
            description: new param
            properties:
                affected:
                    description: new param
                    type: integer
                email_timestamp:
                    description: new param
                    type: integer
                expired:
                    description: new param
                    type: boolean
            type: object
info:
    description: Guerrilla Mail provides a JSON API for temporary email services.
    title: Guerilla Temporary Email
    version: 1.0.0
openapi: 3.1.0
paths:
    /ajax.php:
        get:
            operationId: guerrillaMailApi
            parameters:
                - description: The language code.
                  in: query
                  name: lang
                  schema:
                    type: string
                - description: The sequence number (id) of the oldest email.
                  in: query
                  name: seq
                  schema:
                    type: integer
                - description: The id of the email to fetch.
                  in: query
                  name: email_id
                  schema:
                    type: integer
                - description: The email address to forget.
                  in: query
                  name: email_addr
                  schema:
                    type: string
                - description: The ids of emails to delete.
                  in: query
                  name: email_ids
                  schema:
                    items:
                        description: individual email to delete
                        type: integer
                    type: array
                - description: The function name to call.
                  in: query
                  name: f
                  required: true
                  schema:
                    type: string
                - description: The IP address of the user.
                  in: query
                  name: ip
                  required: true
                  schema:
                    type: string
                - description: The user-agent of the user.
                  in: query
                  name: agent
                  required: true
                  schema:
                    type: string
                - description: The subscriber cookie data.
                  in: query
                  name: SUBSCR
                  schema:
                    type: string
                - description: The username part of an email address.
                  in: query
                  name: email_user
                  schema:
                    type: string
                - description: How many emails to start from (skip).
                  in: query
                  name: offset
                  schema:
                    type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                description: new desc
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    alias:
                                        description: Alias of the temporary email address.
                                        type: string
                                    email_addr:
                                        description: Email address to send or receive emails.
                                        type: string
                                    email_timestamp:
                                        description: Timestamp of the email, in milliseconds since the Unix epoch.
                                        type: number
                                    sid_token:
                                        description: Token used to authenticate API requests.
                                        type: string
                                type: object
                    description: new desc
                default:
                    description: ""
            summary: The Guerrilla Mail API allows you to integrate Guerrilla Mail's email service into your own applications or systems. With this API, you can programmatically create temporary email addresses, send and receive emails, and access various email management functions. It is useful for applications that require temporary or disposable email functionality.
servers:
    - url: https://api.guerrillamail.com
