components:
    examples:
        getIpInfo:
            value:
                ReqExample:
                    ip: 63c5:9988:3792:40aa:0998:db93:8b3e:4dbb
                RespExample:
                    asn: AS31898
                    city: Ashburn
                    continent_code: NA
                    country: US
                    country_area: 9629091
                    country_calling_code: "+1"
                    country_capital: Washington
                    country_code: US
                    country_code_iso3: USA
                    country_name: United States
                    country_population: 327167434
                    country_tld: .us
                    currency: USD
                    currency_name: Dollar
                    in_eu: false
                    ip: 129.80.117.174
                    languages: en-US,es-US,haw,fr
                    latitude: 39.0373
                    longitude: -77.4805
                    network: 129.80.0.0/16
                    org: ORACLE-BMC-31898
                    postal: "20147"
                    region: Virginia
                    region_code: VA
                    timezone: America/New_York
                    utc_offset: "-0400"
                    version: IPv4
info:
    description: The IPAPI service provides location information for a given IP address.
    title: IPAPI Location Lookup
    version: 1.0.0
openapi: 3.1.0
paths:
    /json/:
        get:
            operationId: getIpInfo
            parameters:
                - description: ip value
                  in: query
                  name: ip
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                description: new desc
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    asn:
                                        type: string
                                    city:
                                        type: string
                                    continent_code:
                                        type: string
                                    country:
                                        type: string
                                    country_area:
                                        type: number
                                    country_calling_code:
                                        type: string
                                    country_capital:
                                        type: string
                                    country_code:
                                        type: string
                                    country_code_iso3:
                                        type: string
                                    country_name:
                                        type: string
                                    country_population:
                                        type: integer
                                    country_tld:
                                        type: string
                                    currency:
                                        type: string
                                    currency_name:
                                        type: string
                                    in_eu:
                                        type: boolean
                                    ip:
                                        type: string
                                    languages:
                                        type: string
                                    latitude:
                                        type: number
                                    longitude:
                                        type: number
                                    network:
                                        type: string
                                    org:
                                        type: string
                                    postal:
                                        type: string
                                    region:
                                        type: string
                                    region_code:
                                        type: string
                                    timezone:
                                        type: string
                                    utc_offset:
                                        type: string
                                    version:
                                        type: string
                                type: object
                    description: new desc
                default:
                    description: ""
            summary: This endpoint returns the location information for the calling IP address in JSON format.
servers:
    - url: https://ipapi.co
