components:
    examples:
        _get:
            value:
                ReqExample: {}
                RespExample:
                    quote: I'm giving all Good music artists back the 50% share I have of their masters
info:
    description: |-
        An API to get random Kanye West quotes. You're welcome.

        luke@lukesteuber.com _ assisted.space/join _ lukesteuber.com
        one impossible thing (at a time) AI for accessibility project
    title: Kanye Rest
    version: 1.0.0
openapi: 3.1.0
paths:
    /:
        get:
            operationId: _get
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                description: new desc
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    quote:
                                        type: string
                                type: object
                    description: new desc
                default:
                    description: ""
            summary: Retrieve a random quote from Kanye West.
servers:
    - url: https://api.kanye.rest
