components:
    examples:
        getAdviceById:
            value:
                ReqExample:
                    slip_id: 101
                RespExample:
                    slip:
                        advice: Alway do anything for love, but don't do that.
                        id: 101
        getRandomAdvice:
            value:
                ReqExample: {}
                RespExample:
                    slip:
                        advice: Alway do anything for love, but don't do that.
                        id: 101
        searchAdvice:
            value:
                ReqExample:
                    query: love
                RespExample:
                    query: love
                    slips:
                        - advice: Alway do anything for love, but don't do that.
                          date: "2015-12-08"
                          id: 101
                        - advice: Be a good lover.
                          date: "2014-06-03"
                          id: 174
                        - advice: You can fail at what you don't want. So you might as well take a chance on doing what you love.
                          date: "2017-03-10"
                          id: 184
                        - advice: You can fail at what you don't want. So you might as well take a chance on doing what you love.
                          date: "2016-08-05"
                          id: 185
                        - advice: Never waste an opportunity to tell someone you love them.
                          date: "2016-05-19"
                          id: 202
                    total_results: "5"
    schemas:
        Message:
            description: new param
            properties:
                text:
                    description: new param
                    type: string
                type:
                    description: new param
                    type: string
            type: object
        MessageResponse:
            description: new param
            properties:
                message:
                    $ref: '#/components/schemas/Message'
            type: object
        SearchResponse:
            description: new param
            properties:
                query:
                    description: new param
                    type: string
                slips:
                    description: new param
                    items:
                        $ref: '#/components/schemas/Slip'
                    type: array
                total_results:
                    description: new param
                    type: integer
            type: object
        Slip:
            description: new param
            properties:
                advice:
                    description: new param
                    type: string
                slip_id:
                    description: new param
                    type: integer
            type: object
        SlipResponse:
            description: new param
            properties:
                slip:
                    $ref: '#/components/schemas/Slip'
            type: object
info:
    description: The Advice Slip JSON API provides random pieces of advice. It currently gives out over 10 million pieces of advice every year.
    title: Random Advice
    version: 1.0.0
openapi: 3.1.0
paths:
    /advice:
        get:
            operationId: getRandomAdvice
            parameters:
                - description: To define your own callback function name and return the JSON in a function wrapper (as JSONP).
                  in: query
                  name: callback
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                description: new desc
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    slip:
                                        description: Returns a random advice slip.
                                        properties:
                                            advice:
                                                description: Returns a random advice slip.
                                                type: string
                                            id:
                                                description: Unique identifier for the advice slip.
                                                type: number
                                        type: object
                                type: object
                    description: new desc
                default:
                    description: ""
            summary: Returns a random advice slip as a slip object.
    /advice/{slip_id}:
        get:
            operationId: getAdviceById
            parameters:
                - description: The ID of the advice slip.
                  in: path
                  name: slip_id
                  required: true
                  schema:
                    default: 101
                    type: integer
                - description: To define your own callback function name and return the JSON in a function wrapper (as JSONP).
                  in: query
                  name: callback
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                description: new desc
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    slip:
                                        description: Return slip object with advice slip information.
                                        properties:
                                            advice:
                                                description: The advice slip with the corresponding {slip_id}.
                                                type: string
                                            id:
                                                description: The unique identifier of the advice slip.
                                                type: number
                                        type: object
                                type: object
                    description: new desc
                default:
                    description: ""
            summary: If an advice slip is found with the corresponding {slip_id}, a slip object is returned.
    /advice/search/{query}:
        get:
            operationId: searchAdvice
            parameters:
                - description: The search term.
                  in: path
                  name: query
                  required: true
                  schema:
                    default: math
                    type: string
                - description: To define your own callback function name and return the JSON in a function wrapper (as JSONP).
                  in: query
                  name: callback
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                description: new desc
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    query:
                                        description: Query term to search for advice slips.
                                        type: string
                                    slips:
                                        description: Array of advice slips that match the search term {query}. Each slip object contains advice text and a slip ID.
                                        items:
                                            description: Array item
                                            properties:
                                                advice:
                                                    description: This parameter returns an advice slip that matches the search term. It is a string type.
                                                    type: string
                                                date:
                                                    description: Date in which the advice slips were searched for.
                                                    type: string
                                                id:
                                                    description: ID of the advice slip.
                                                    type: number
                                            type: object
                                        type: array
                                    total_results:
                                        description: Total number of advice slips found for the corresponding search term.
                                        type: string
                                type: object
                    description: new desc
                default:
                    description: ""
            summary: If an advice slip is found containing the corresponding search term in {query}, an array of slip objects is returned inside a search object.
servers:
    - url: https://api.adviceslip.com
