components:
    examples:
        getComicById:
            value:
                ReqExample:
                    comicId: 2973
                RespExample:
                    alt: They left the belt drive in place but switched which wheel was powered, so people could choose between a regular ride, a long ride, and a REALLY long ride.
                    day: "16"
                    img: https://imgs.xkcd.com/comics/ferris_wheels.png
                    link: ""
                    month: "8"
                    news: ""
                    num: 2973
                    safe_title: Ferris Wheels
                    title: Ferris Wheels
                    transcript: ""
                    year: "2024"
        getCurrentComic:
            value:
                ReqExample: {}
                RespExample:
                    alt: They left the belt drive in place but switched which wheel was powered, so people could choose between a regular ride, a long ride, and a REALLY long ride.
                    day: "16"
                    img: https://imgs.xkcd.com/comics/ferris_wheels.png
                    link: ""
                    month: "8"
                    news: ""
                    num: 2973
                    safe_title: Ferris Wheels
                    title: Ferris Wheels
                    transcript: ""
                    year: "2024"
    schemas:
        Comic:
            description: new param
            properties:
                alt:
                    description: The alt text of the comic.
                    type: string
                day:
                    description: The day the comic was published.
                    type: string
                img:
                    description: The URL of the comic image.
                    type: string
                link:
                    description: A link to the comic.
                    type: string
                month:
                    description: The month the comic was published.
                    type: string
                news:
                    description: Any news related to the comic.
                    type: string
                num:
                    description: The comic ID.
                    type: integer
                safe_title:
                    description: A safe version of the comic title.
                    type: string
                title:
                    description: The title of the comic.
                    type: string
                transcript:
                    description: The transcript of the comic.
                    type: string
                year:
                    description: The year the comic was published.
                    type: string
            type: object
info:
    description: API to fetch XKCD comics and metadata.
    title: XKCD
    version: 1.0.0
openapi: 3.1.0
paths:
    /{comicId}/info.0.json:
        get:
            operationId: getComicById
            parameters:
                - description: The ID of the comic to fetch.
                  in: path
                  name: comicId
                  required: true
                  schema:
                    default: 2973
                    type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                description: new desc
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    alt:
                                        description: Alternative text description of the comic.
                                        type: string
                                    day:
                                        description: The day the XKCD comic was published, in the format "YYYY-MM-DD".
                                        type: string
                                    img:
                                        description: The URL of the image file for the XKCD comic.
                                        type: string
                                    link:
                                        description: The link to the specific XKCD comic and its metadata.
                                        type: string
                                    month:
                                        description: The month when the XKCD comic was published, in format "mm-yyyy". Default is the current month.
                                        type: string
                                    news:
                                        description: The news related to the specified XKCD comic and its metadata.
                                        type: string
                                    num:
                                        description: Comic ID to fetch the specific XKCD comic and its metadata.
                                        type: number
                                    safe_title:
                                        description: Title of the XKCD comic strip, stripped of any special characters or formatting.
                                        type: string
                                    title:
                                        description: Title of the XKCD comic.
                                        type: string
                                    transcript:
                                        description: Transcript of the XKCD comic, containing the dialogue and captions.
                                        type: string
                                    year:
                                        description: Year of the XKCD comic, in YYYY format.
                                        type: string
                                type: object
                    description: new desc
                default:
                    description: ""
            summary: Fetch a specific XKCD comic and its metadata by comic ID.
    /info.0.json:
        get:
            operationId: getCurrentComic
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                description: new desc
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    alt:
                                        description: The alternative text description of the XKCD comic.
                                        type: string
                                    day:
                                        description: Specify the day to fetch the XKCD comic and its metadata, in format yyyy-mm-dd. Default is today.
                                        type: string
                                    img:
                                        description: URL of the image file for the current XKCD comic.
                                        type: string
                                    link:
                                        description: Link to the XKCD comic image.
                                        type: string
                                    month:
                                        description: Specify the month of the XKCD comic to fetch, in format "yyyy-mm".
                                        type: string
                                    news:
                                        description: The current XKCD comic and its metadata.
                                        type: string
                                    num:
                                        description: Specifies the number of the XKCD comic to fetch.
                                        type: number
                                    safe_title:
                                        description: Title of the comic that is safe for all audiences.
                                        type: string
                                    title:
                                        description: Title of the XKCD comic.
                                        type: string
                                    transcript:
                                        description: Transcript of the comic, containing the dialogue and descriptions.
                                        type: string
                                    year:
                                        description: The year of the XKCD comic.
                                        type: string
                                type: object
                    description: new desc
                default:
                    description: ""
            summary: Fetch the current XKCD comic and its metadata.
servers:
    - url: https://xkcd.com
